name: final_lnk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  cupertino_icons:
  dartz:
  flutter_screenutil:
  flutter_svg:
  data_connection_checker_tv:
  flutter_native_splash:
  easy_localization:
  url_launcher:
  skeletonizer:
  cached_network_image:
  dio:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  google_fonts:
  image_picker:
  pinput:
  photo_view:
  shared_preferences:
  smooth_page_indicator:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/Icon.png"
  adaptive_icon_foreground: "assets/imgs/Icon.png"
  adaptive_icon_background: "#00ffff"



flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/imgs/
    - assets/imgs/nav_bar_assets/
    - assets/imgs/on_boarding/
    - assets/imgs/properties_icons/
    - assets/imgs/menu_icons/
    - assets/imgs/property_details_icon/
