import 'dart:async';

import 'package:easy_localization/easy_localization.dart';

class LangKeys {
  static String get onBoardingTitle1 => 'onBoardingTitle1'.tr();
  static String get onBoardingTitle2 => 'onBoardingTitle2'.tr();
  static String get onBoardingTitle3 => 'onBoardingTitle3'.tr();
  static String get onBoardingSubTitle1 => 'onBoardingSubTitle1'.tr();
  static String get onBoardingSubTitle2 => 'onBoardingSubTitle2'.tr();
  static String get onBoardingSubTitle3 => 'onBoardingSubTitle3'.tr();
  static String get skip => 'skip'.tr();
  static String get getStarted => 'getStarted'.tr();
  static String get start => 'start'.tr();
  static String get next => 'next'.tr();
  static String get phoneNumber => 'phoneNumber'.tr();
  static String get password => 'password'.tr();
  static String get signIn => 'signIn'.tr();
  static String get signUp => 'signUp'.tr();
  static String get dontHave => 'dontHave'.tr();
  static String get forgetPass => 'forgetPass'.tr();
  static String get remember => 'remember'.tr();
  static String get fieldRequired => 'fieldRequired'.tr();
  static String get phoneValid => 'phoneValid'.tr();
  static String get passValid => 'passValid'.tr();
  static String get selectAccType => 'selectAccType'.tr();
  static String get selectRoleDes => 'selectRoleDes'.tr();
  static String get agency => 'agency'.tr();
  static String get agencyDes => 'agencyDes'.tr();
  static String get freelance => 'freelance'.tr();
  static String get freelanceDes => 'freelanceDes'.tr();
  static String get continueButton => 'continue'.tr();
  static String get createAcc => 'createAcc'.tr();
  static String get fullName => 'fullName'.tr();
  static String get email => 'email'.tr();
  static String get city => 'city'.tr();
  static String get serviceArea => 'serviceArea'.tr();
  static String get agencyName => 'agencyName'.tr();
  static String get address => 'address'.tr();
  static String get select => 'select'.tr();
  static String get validEmail => 'validEmail'.tr();
  static String get verifyCode => 'verifyCode'.tr();
  static String get verifyCodeDes => 'verifyCodeDes'.tr();
  static String get resend => 'resend'.tr();
  static String get submit => 'submit'.tr();
  static String get didntReceive => 'didntReceive'.tr();
  static String get otpVerified => 'otpVerified'.tr();
  static String get forgetPassTitle => 'forgetPassTitle'.tr();
  static String get forgetPassDes => 'forgetPassDes'.tr();
  static String get sendCode => 'sendCode'.tr();
  static String get sendSuccess => 'sendSuccess'.tr();
  static String get resetPassword => 'resetPassword'.tr();
  static String get resetPasswordSuccess => 'resetPasswordSuccess'.tr();
}
